[package]
name = "folded"
version = "0.1.0"
description = "Telegram Cloud Storage Native App"
authors = ["Antigravity"]
edition = "2021"

[dependencies]
tauri = { version = "2.1.1", features = ["macos-private-api", "image-png", "tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
grammers-client = "0.9"
grammers-session = "0.9"
grammers-tl-types = "0.9"
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "sqlite", "macros"] }
dav-server = "0.5"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
mime_guess = "2.0"
urlencoding = "2.1"
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4"
base64 = "0.21"
walkdir = "2"
tauri-plugin-dialog = "2.7.0"
tauri-plugin-autostart = "2.1.0"
axum = "0.8.8"
tower-http = { version = "0.6.8", features = ["fs", "cors"] }
tower = { version = "0.5.3", features = ["util", "make"] }
futures-util = "0.3.32"
bytes = "1.11.1"
http_02 = { version = "0.2", package = "http" }
http_body_04 = { version = "0.4", package = "http-body" }
zip = "2.1.0"
tokio-stream = { version = "0.1.18", features = ["fs"] }
notify = "6.1.1"
tokio-util = "0.7.18"

[build-dependencies]
tauri-build = { version = "2.1.1", features = [] }
